

DROP TABLE cuentas_c CASCADE CONSTRAINTS;

DROP TABLE e_comerciales CASCADE CONSTRAINTS;

DROP TABLE equipos CASCADE CONSTRAINTS;

DROP TABLE establecimientos CASCADE CONSTRAINTS;

DROP TABLE gimnasios CASCADE CONSTRAINTS;

DROP TABLE habitaciones CASCADE CONSTRAINTS;

DROP TABLE hoteles CASCADE CONSTRAINTS;

DROP TABLE internet CASCADE CONSTRAINTS;

DROP TABLE lavados CASCADE CONSTRAINTS;

DROP TABLE piscinas CASCADE CONSTRAINTS;

DROP TABLE planes_c CASCADE CONSTRAINTS;

DROP TABLE prestamos CASCADE CONSTRAINTS;

DROP TABLE productos CASCADE CONSTRAINTS;

DROP TABLE productos_c CASCADE CONSTRAINTS;

DROP TABLE productos_e CASCADE CONSTRAINTS;

DROP TABLE productos_ecomerciales CASCADE CONSTRAINTS;

DROP TABLE productos_plan CASCADE CONSTRAINTS;

DROP TABLE reservas CASCADE CONSTRAINTS;

DROP TABLE reservas_servicios CASCADE CONSTRAINTS;

DROP TABLE s_consumidos CASCADE CONSTRAINTS;

DROP TABLE s_servicios CASCADE CONSTRAINTS;

DROP TABLE salones CASCADE CONSTRAINTS;

DROP TABLE servicios CASCADE CONSTRAINTS;

DROP TABLE spas CASCADE CONSTRAINTS;

DROP TABLE usuarios CASCADE CONSTRAINTS;