INSERT INTO hoteles VALUES ('Hilton','Bogotá D.C');

INSERT INTO hoteles VALUES ('Dann','Bogotá D.C');

INSERT INTO habitaciones VALUES (1,4,1,'Suite','cama',320000,'Hilton');

INSERT INTO planes_c VALUES (1,'Estandar',25,35,45,45,380000,TO_DATE('2023-12-28','YYYY-MM-DD'),4,0,0);

INSERT INTO usuarios VALUES (1,'Carolina Bennedeti','c.benedeti@gmail.com','cliente','Hilton');

INSERT INTO cuentas_c VALUES (1,1,'28-11-2023','28-11-2023',1);

INSERT INTO reservas VALUES (1,TO_DATE('2023-11-28','YYYY-MM-DD'),TO_DATE('2023-12-28','YYYY-MM-DD'),30,2,1,1,1,1);


-- Insertar dos recepcionistas
INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (3, 'Ana Sánchez', 'ana.sanchez@example.com', 'recepcionista', 'Dann');
    
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (4, 'Carlos López', 'carlos.lopez@example.com', 'recepcionista', 'Hilton');

-- Insertar cuatro empleados
INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (5, 'Laura González', 'laura.gonzalez@example.com', 'empleado', 'Dann');
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (6, 'Miguel Martínez', 'miguel.martinez@example.com', 'empleado', 'Hilton');
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (7, 'Sofía Fernández', 'sofia.fernandez@example.com', 'empleado', 'Hilton');
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (8, 'David García', 'david.garcia@example.com', 'empleado', 'Hilton');

-- Insertar cuatro clientes
INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (9, 'Elena Torres', 'elena.torres@example.com', 'cliente', 'Dann');
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (10, 'Javier Ruiz', 'javier.ruiz@example.com', 'cliente', 'Dann');
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (11, 'Lucía Díaz', 'lucia.diaz@example.com', 'cliente', 'Dann');
    INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES
    (12, 'Diego Herrera', 'diego.herrera@example.com', 'cliente', 'Hilton');

-- Insertar un administrador
INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, ROL, nombrehotel) 
VALUES (13, 'María Rodríguez', 'maria.rodriguez@example.com', 'administrador', 'Dann');




-- Habitación Tipo 2
INSERT INTO HABITACIONES (IDHABITACION, CAPACIDAD, DISPONIBLE, TIPO, DOTACION, PRECIONOCHE, nombrehotel) 
VALUES (2, 2, 0, 'Estándar', 'Televisión, Baño, Aire Acondicionado', 80, 'Dann');

-- Habitación Tipo 3
INSERT INTO HABITACIONES (IDHABITACION, CAPACIDAD, DISPONIBLE, TIPO, DOTACION, PRECIONOCHE, nombrehotel) 
VALUES (3, 3, 0, 'Suite', 'Televisión, Baño, Jacuzzi', 150, 'Hilton');

-- Habitación Tipo 4 (Opcional)
INSERT INTO HABITACIONES (IDHABITACION, CAPACIDAD, DISPONIBLE, TIPO, DOTACION, PRECIONOCHE, nombrehotel) 
VALUES (4, 4, 1, 'Suite de Lujo', 'Televisión, Baño, Minibar, Jacuzzi, Vista al Mar', 250, 'Dann');

-- Habitación Tipo 1
INSERT INTO HABITACIONES (IDHABITACION, CAPACIDAD, DISPONIBLE, TIPO, DOTACION, PRECIONOCHE, nombrehotel) 
VALUES (5, 2, 1, 'Economica', 'Televisión, Baño', 50, 'Hilton');



INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(1,100000,60,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(2,0,20,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(3,0,30,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(4,0,1200,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(5,100000,60,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(6,10000,3,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(7,350000,20,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(8,100000,60,'Dann',1);
INSERT INTO SERVICIOS(IDSERVICIO,COSTOTOTAL,CAPACIDAD,nombrehotel,IDPLANCONSUMO)
VALUES(9,300000,200,'Dann',1);
--SERVICOS
INSERT INTO ESTABLECIMIENTOS(IDSERVICIO, ESTILO, TIPO)
VALUES(1,'Comida Italiana','restaurante');

INSERT INTO PISCINAS(IDSERVICIO, PROFUNDIDAD, HORAINICIO,HORAFIN)
VALUES(2,5,TO_DATE('12:00','hh:mi'),TO_DATE('1:00','hh:mi'));

INSERT INTO GIMNASIOS(IDSERVICIO,NUMEROMAQUINA,HORAINICIO,HORAFIN)
VALUES(3,5,TO_DATE('3:00','hh:mi'),TO_DATE('4:00','hh:mi'));

INSERT INTO INTERNET(IDSERVICIO,BANDAANCHA)
VALUES(4,4000);

INSERT INTO LAVADOS(IDSERVICIO,NUMEROPRENDAS,PARESZAPATOS)
VALUES(5,4,2);

INSERT INTO PRESTAMOS(IDSERVICIO,UTENSILIO,CANTIDAD,IDCUENTA,ENPRESTAMO,COSTOPENALIZACION,ESTADO)
VALUES(6,'secador',1,1,1,10000,0);

INSERT INTO E_COMERCIALES(IDSERVICIO,NOMBRE,TIPO)
VALUES(7,'Tienda','Joyeria');

INSERT INTO SPAS(IDSERVICIO,NOMBRE)
VALUES(8,'Serenidad');

INSERT INTO SALONES(IDSERVICIO,TIPO)
VALUES(9,'reunion');

--RESERVAS SERVICIOS
INSERT INTO RESERVAS_SERVICIOS(IDSERVICIO,IDHABITACION,FECHARESERVA,DURACION)
VALUES(1,1,TO_DATE('2023/11/20 12:00','yyyy/mm/dd hh:mi'),30);



--RF1

SELECT UNIQUE(ROL) FROM USUARIOS;

--RF2

SELECT * FROM USUARIOS;

--RF3

SELECT TIPO FROM HABITACIONES;


--RF4

SELECT * FROM HABITACIONES;

--RF5
SELECT * FROM SALONES;

SELECT * FROM SPAS;

SELECT * FROM E_COMERCIALES;

SELECT * FROM PRESTAMOS;

SELECT * FROM LAVADOS;

SELECT * FROM INTERNET;

SELECT * FROM GIMNASIOS;

SELECT * FROM ESTABLECIMIENTOS;

SELECT * FROM PISCINAS;

SELECT * FROM SERVICIOS;

--RF6

SELECT * FROM PLANES_C;

--RF7

SELECT * FROM RESERVAS;

--RF8

SELECT * FROM RESERVAS_SERVICIOS;

--RF9

SELECT IDCUENTA,CHECKIN FROM CUENTAS_C;

--RF10

SELECT IDCUENTA,CHECKOUT FROM CUENTAS_C;

--RF11

SELECT IDCUENTA,CHECKOUT FROM CUENTAS_C;